### ISSUE TITLE
Missing script

### ISSUE THREAD

**Issue by genomewalker** [chassenr/taxdb-integration#1]
Hi
would be possible to get the https://github.com/chassenr/taxdb-integration/blob/master/config/config_collect.yaml#L167 in the repo?

Thanks

**Comment by chassenr** [comment]
The [script](https://github.com/chassenr/taxdb-integration/blob/master/scripts/gtdb_to_taxdump_mod.py) has now been added (17ac3108e110ba7ca7c13150222d749cc0bd6502).

**Comment by genomewalker** [comment]
Thanks!
